backend:
  name: git-gateway
  branch: main

media_folder: "assets/uploads"
public_folder: "/assets/uploads"

collections:
  - name: "photography"
    label: "Photography"
    files:
      - name: "black_and_white"
        label: "Black & White"
        file: "content/photography-bw.json"
        format: "json"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
              - { label: "Description", name: "alt", widget: "string", required: false }
      - name: "colour"
        label: "Colour"
        file: "content/photography-colour.json"
        format: "json"
        fields:
          - label: "Images"
            name: "images"
            widget: "list"
            summary: "{{fields.caption}}"
            fields:
              - { label: "Image", name: "image", widget: "image" }
              - { label: "Caption", name: "caption", widget: "string", required: false }
              - { label: "Description", name: "alt", widget: "string", required: false }
